---

resources:
  - name: todo-aggregator-src
    type: git
    icon: git
    source:
      uri: https://github.com/tlwr/todo-aggregator.git
      branch: main


jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: todo-aggregator-src
        trigger: true

      - set_pipeline: todo-aggregator
        file: todo-aggregator-src/ci/pipeline.yml

  - name: test
    serial: true
    public: true
    plan:
      - get: todo-aggregator-src
        passed: [set-pipeline]
        trigger: true

      - task: test
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: golang

          inputs:
            - name: todo-aggregator-src
              path: .

          run:
            path: go
            args:
              - test
              - -v
              - ./...
              - -ginkgo.v
