---
resource_types:
  - name: registry-tag
    type: registry-image
    source:
      repository: ghcr.io/tlwr/registry-tag-resource
      tag: 6d98ababb33b88eb6d9a0d3d2824c3efe500c18b

resources:
  - name: golang-img-tag
    type: registry-tag
    icon: tag
    check_every: 60m
    source:
      uri: https://hub.docker.com/v2/repositories/library/golang
      pages: 10
      regexp: '^[0-9]+[.][0-9]+[.][0-9]+-alpine'
      semver:
        matcher: '>= 1.16'

  - name: todo-aggregator-src
    type: git
    icon: git
    source:
      uri: https://github.com/tlwr/todo-aggregator.git
      branch: main

  - name: todo-aggregator-img
    type: registry-image
    icon: docker
    source:
      repository: ghcr.io/tlwr/todo-aggregator
      username: ((docker-secrets.username))
      password: ((docker-secrets.password))


jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: todo-aggregator-src
        trigger: true

      - set_pipeline: todo-aggregator
        file: todo-aggregator-src/ci/pipeline.yml

  - name: test
    serial: true
    public: true
    plan:
      - get: todo-aggregator-src
        passed: [set-pipeline]
        trigger: true

      - task: test
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: golang

          inputs:
            - name: todo-aggregator-src
              path: .

          run:
            path: go
            args:
              - test
              - -v
              - ./...
              - -ginkgo.v

  - name: build
    serial: true
    public: true
    plan:
      - get: todo-aggregator-src
        passed: [test]
        trigger: true

      - get: golang-img-tag
        trigger: true

      - load_var: golang-version
        file: golang-img-tag/tag

      - task: build-img
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
              tag: 0.3.0

          inputs:
            - name: todo-aggregator-src
              path: .

          outputs:
            - name: image

          params:
            BUILD_ARG_golang_version: ((.:golang-version))

          run:
            path: build

      - put: todo-aggregator-img
        params:
          image: image/image.tar
          additional_tags: todo-aggregator-src/.git/ref
        get_params:
          skip_download: true
